services:
  grott:
    image: ghcr.io/herbertmt978/grott:0.1.12
    container_name: grott
    restart: unless-stopped
    init: true
    user: "10001:10001"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "5279:5279"
    volumes:
      - ./grott.ini:/app/grott.ini:ro
    environment:
      - TZ=Europe/London
      - gmode=proxy
      - gblockcmd=True
      - gtime=server
      - gsendbuf=False
      - ginvtype=default
      - glayoutstrict=False
      - glayoutautofamily=True
      - gnomqtt=True
