services:
  grott:
    image: ghcr.io/herbertmt978/grott:0.1.8-beta
    container_name: grott
    restart: unless-stopped
    ports:
      - "5279:5279"
    volumes:
      - ./grott.ini:/app/grott.ini:ro
    environment:
      - TZ=Europe/London
      - gmode=proxy
      - gblockcmd=True
      - gtime=server
      - gsendbuf=False
      - ginvtype=default
      - glayoutstrict=False
      - glayoutautofamily=True
      - gnomqtt=True
